### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by Arsca** [mark-hahn/live-archive#11]
[Enter steps to reproduce below:]

1. When starting to edit the code.
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.15

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098:15)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:693:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2530:33)
  at EditorMgr.module.exports.EditorMgr.setViewPos (/Users/arsca/.atom/packages/live-archive/lib/editor-mgr.coffee:94:14)
  at /Users/arsca/.atom/packages/live-archive/lib/editor-mgr.coffee:410:37

```

### Commands

```
     -7:07.8.0 vim-mode:reset-command-mode (input.hidden-input)
     -6:16.3.0 git-plus:menu (input.hidden-input)
     -6:14.2.0 core:confirm (input.hidden-input)
  3x -6:13.7.0 core:move-down (input.hidden-input)
     -6:12.5.0 core:confirm (input.hidden-input)
     -1:34.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:32.5.0 core:confirm (input.hidden-input)
     -1:31.3.0 core:select-all (input.hidden-input)
     -1:30.8.0 core:paste (input.hidden-input)
  2x -1:29.3.0 core:save (input.hidden-input)
     -0:35.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:33.1.0 core:confirm (input.hidden-input)
     -0:31.7.0 core:select-all (input.hidden-input)
     -0:31 core:paste (input.hidden-input)
  4x -0:29 core:backspace (input.hidden-input)
     -0:24 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-bold-syntax"
    ],
    "projectHome": "/Users/arsca/Development/SIPECO/gitlab/sipeco",
    "disabledPackages": [
      "tualo-git-context",
      "terminal-status",
      "git-difftool",
      "atomatigit",
      "linter-jscs",
      "atom-minjs",
      "symbols-view",
      "tree-view-open-files",
      "fonts"
    ],
    "ignoredNames": [
      "node_modules",
      "assets/js/vendor",
      "assets/js/TimelineJS",
      "assets/js/oracle"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-handlebars, v0.5.0
atom-jasmine, v0.6.0
atom-runner, v2.4.1
atom-solarized-dark-ui, v0.25.0
autoclose-html, v0.18.0
autocomplete-modules, v0.3.6
autocomplete-polymer, v0.2.3
autohide-tree-view, v0.20.2
block-cursor, v0.13.1
block-travel, v1.0.2
color-picker, v2.0.7
docblockr, v0.7.2
duplicate-line-or-selection, v0.5.0
ember-cli-helper, v0.7.2
ember-snippets, v1.2.1
emmet, v2.3.10
file-icons, v1.5.7
git-log, v0.4.1
git-plus, v5.2.1
git-tab-status, v1.9.2
javascript-snippets, v1.0.0
johns-work-arounds, v0.18.0
js-patterns-atom-snippets, v0.2.1
jsformat, v0.9.0
json-colorer, v0.3.0
language-ejs, v0.1.0
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-gitignore, v0.2.0
last-cursor-position, v0.9.0
linter, v1.0.0
linter-csslint, v0.0.13
linter-eslint, v0.5.10
linter-htmlhint, v0.0.16
live-archive, v0.1.15
local-history, v3.2.3
markdown-format, v2.5.1
minimap, v4.10.0
minimap-git-diff, v4.1.3
node-debugger, v1.1.0
pretty-json, v0.3.3
project-manager, v1.15.10
project-view, v0.1.2
react, v0.12.0
remote-edit, v1.8.2
remote-sync, v3.1.2
solarized-dark-bold-syntax, v0.2.0
ssh-config, v0.10.1
symbols-tree-view, v0.9.3
tabs-to-spaces, v0.11.0
vim-mode, v0.53.0
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I just want everyone to know I haven't forgotten about the issues.  I've just been too busy.  I'll get to them by this weekend.
