### ISSUE TITLE
Uncaught TypeError: atom.project.getRepo is not a function

### ISSUE THREAD

**Issue by AdamKyle** [mark-hahn/live-archive#14]
[Enter steps to reproduce below:]
1. Open Atom
2. Open File that has history
3. click archive
4. click git
5. watch error.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.4
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.15
### Stack Trace

Uncaught TypeError: atom.project.getRepo is not a function

```
At /Users/adambalan/.atom/packages/live-archive/lib/editor-mgr.coffee:176

TypeError: atom.project.getRepo is not a function
    at EditorMgr.module.exports.EditorMgr.findGitHead (/Users/adambalan/.atom/packages/live-archive/lib/editor-mgr.coffee:176:33)
    at EditorMgr.<anonymous> (/Users/adambalan/.atom/packages/live-archive/lib/editor-mgr.coffee:500:27)
    at EditorMgr.module.exports.EditorMgr.loadEditor (/Users/adambalan/.atom/packages/live-archive/lib/editor-mgr.coffee:548:12)
    at ReplayView.module.exports.ReplayView.handle (/Users/adambalan/.atom/packages/live-archive/lib/replay-view.coffee:145:29)
    at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "railscasts-prime-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
language-gherkin, v1.0.2
live-archive, v0.1.15
railscasts-prime-syntax, v1.0.1

# Dev
No dev packages
```

**Comment by M0rtenB** [comment]
+1

**Comment by mliq** [comment]
+1

**Comment by mliq** [comment]
[Enter steps to reproduce below:]

1. Open File that has history
2. click archive
3. click git

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.15


### Stack Trace

Uncaught TypeError: atom.project.getRepo is not a function

```
At /Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/editor-mgr.coffee:114

TypeError: atom.project.getRepo is not a function
    at EditorMgr.module.exports.EditorMgr.findGitHead (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/editor-mgr.coffee:114:33)
    at EditorMgr.<anonymous> (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/editor-mgr.coffee:335:44)
    at EditorMgr.module.exports.EditorMgr.loadEditor (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/editor-mgr.coffee:332:13)
    at ReplayView.module.exports.ReplayView.handle (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/replay-view.coffee:65:16)
    at space-pen-div.<anonymous> (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:42.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:42.5.0 markdown-writer:indent-list-line (atom-text-editor.editor.is-focused)
     -0:42.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:42.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:42.5.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:42.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:41.9.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:41.9.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:41.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:39.9.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:39.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:39.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:39.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:38.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:35 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "path-hyperclick",
      "file-hyperclick",
      "navigation-history",
      "split-diff",
      "tree-view-autoresize",
      "symbol-gen",
      "semanticolor",
      "fonts",
      "pigments",
      "rnn-writer",
      "language-javascript-semantic",
      "language-javascript-jsx",
      "git-diff-details",
      "language-javascript-better",
      "webbox-color",
      "atom-beautify",
      "tree-view-git-branch",
      "tree-view-git-status",
      "save-session",
      "js-refactor",
      "refactor",
      "git-history",
      "unsaved-changes",
      "Tern",
      "language-markdown",
      "markdown-preview",
      "autocomplete-ctags",
      "atom-ctags",
      "ctags-status",
      "change-case",
      "markdown-assistant"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view-filter",
      "bookmarks",
      "merge-conflicts",
      "pinned-tabs",
      "markdown-pdf",
      "copy-filename",
      "git-diff-popup",
      "live-archive"
    ],
    "projectHome": "/Users/mliquori/Dropbox/tech/projects",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-syntax, v0.4.6
atom-ternjs, v0.14.2
autoclose-html, v0.23.0
autocomplete-modules, v1.5.1
block-travel, v1.0.4
color-picker, v2.1.1
copy-filename, v1.0.1
docblockr, v0.7.3
editorconfig, v1.4.1
file-icons, v1.7.15
git-diff-popup, v0.1.8
goto-last-edit, v0.3.2
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-markdown, v0.1.3
indent-guide-improved, v1.4.9
js-hyperclick, v1.4.2
language-babel, v2.28.0
language-diff, v0.4.0
last-cursor-position, v0.9.0
line-diff-details, v1.3.5
linter, v1.11.11
linter-eslint, v7.2.2
live-archive, v0.1.15
local-history, v3.3.0
markdown-image-helper, v1.0.4
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.4.0
markdown-writer, v2.3.4
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-cursorline, v0.2.0
pinned-tabs, v0.2.5
preview-inline, v1.0.4
project-manager, v2.9.7
recent-files-fuzzy-finder, v0.2.4
remember-file-positions, v0.2.2
tree-view-filter, v0.4.1

# Dev
No dev packages
```

**Comment by a7madgamal** [comment]
any updates on this? :(

**Comment by mark-hahn** [comment]
Sorry, even though I have the same problem, I don't have time to work on
it.  Want to take a stab at fixing it?

**Comment by a7madgamal** [comment]
this should fix it #21 :)

**Comment by a7madgamal** [comment]
any chance for an update with my fix? :D

**Comment by mark-hahn** [comment]
I don't have a dev environment set up.  Can you take ownership and publish it?
