### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mliq** [mark-hahn/live-archive#18]
[Enter steps to reproduce below:]

1. New project
2. Add project folder
3. Click on 'Archive disabled'

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.15

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:450:3)
    at Object.module.exports.openReviewEditor (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/live-archive.coffee:90:30)
    at space-pen-a.<anonymous> (/Users/mliquori/Dropbox/config/atom/packages/live-archive/lib/status-bar-view.coffee:10:28)
    at space-pen-a.jQuery.event.dispatch (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-a.elemData.handle (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:28.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:27.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:22.7.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "symbols-view",
      "Tern",
      "atom-ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-ctags, v4.5.2
autoclose-html, v0.23.0
autocomplete-ctags, v0.4.1
autocomplete-modules, v1.5.2
block-travel, v1.0.4
change-case, v0.6.0
close-on-left, v0.5.0
color-picker, v2.1.1
copy-filename, v1.0.1
ctags-status, v1.3.4
docblockr, v0.7.3
editorconfig, v1.4.1
file-icons, v1.7.16
fonts, v1.5.0
git-diff-details, v1.3.0
goto-last-edit, v0.3.2
highlight-selected, v0.11.2
hyperclick, v0.0.37
hyperclick-markdown, v0.1.3
indent-guide-improved, v1.4.9
js-hyperclick, v1.4.2
js-refactor, v0.7.3
language-babel, v2.29.2
language-diff, v0.4.0
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
language-markdown, v0.14.1
last-cursor-position, v0.9.0
line-diff-details, v1.3.5
linter, v1.11.14
linter-eslint, v7.2.4
live-archive, v0.1.15
local-history, v3.3.0
markdown-assistant, v0.2.0
markdown-image-helper, v1.0.4
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
one-tab, v0.10.0
pigments, v0.31.0
pinned-tabs, v0.3.1
preview-inline, v1.0.5
project-manager, v2.9.7
recent-files-fuzzy-finder, v0.2.4
refactor, v0.9.2
remember-file-positions, v0.2.2
rnn-writer, v0.0.1
save-session, v0.15.7
semanticolor, v0.2.2
simple-panes, v1.0.1
symbol-gen, v1.3.1
tree-view-autoresize, v1.2.0
tree-view-filter, v0.4.1
tree-view-git-branch, v0.1.2
tree-view-git-status, v1.0.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by a7madgamal** [comment]
is this still the case for the latest version?

**Comment by mliq** [comment]
@a7madgamal Just got this error again now on latest version of everything.

[Enter steps to reproduce:]

1. Open project which already has .live-archive
2. Status bar says archive-disabled.
3. Click to enable archive.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package 0.1.15


### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.normalize (path.js:1179:5)
    at Object.openReviewEditor (/packages/live-archive/lib/live-archive.coffee:90:30)
    at /packages/live-archive/lib/status-bar-view.coffee:10:28)
    at /packages/live-archive/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/live-archive/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:41.3.0 project-manager:list-projects (input.hidden-input)
     -0:39.2.0 editor:consolidate-selections (input.hidden-input)
     -0:39.2.0 core:cancel (input.hidden-input)
     -0:38.4.0 project-manager:list-projects (input.hidden-input)
     -0:37 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-json-color 0.6.0 
atom-material-syntax 1.0.2 
atom-typescript 11.0.2 
autocomplete-modules 1.6.9 
block-travel 1.0.5 
busy-signal 1.3.0 
case-keep-replace 0.5.0 
change-case 0.6.5 
close-on-left 0.8.0 
coffee-compile 0.25.0 
color-picker 2.2.5 
copy-filename 1.0.1 
docblockr 0.9.4 
editorconfig 2.2.2 
esformatter 2.2.1 
fast-eslint 3.13.0 
find-selection 0.16.0 
fold-search-results 1.0.5 
git-blame 1.0.1 
git-diff-details 1.4.0 
git-history 3.3.0 
git-status 0.3.4 
goto-last-edit 0.3.2 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.10.1 
jsformat 0.9.3 
language-babel 2.57.7 
language-diff 0.7.0 
language-r 0.4.1 
language-typescript-grammars-only 1.6.0 
last-cursor-position 0.9.2 
line-diff-details 1.8.0 
linter 2.1.4 
linter-coffeescript 1.0.0 
linter-eslint 8.1.6 
linter-json-lint 0.1.1 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.4 
linter-stylelint undefined 
linter-ui-default 1.2.3 
live-archive 0.1.15 
markdown-folder 0.5.0 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
nord-atom-ui 0.11.0 
pigments 0.39.1 
pinned-tabs 0.4.2 
pretty-json 1.6.3 
project-manager 3.3.4 
recent-files-fuzzy-finder 0.3.1 
Sublime-Style-Column-Selection 1.7.4 
todo-show 1.11.0 
toggle-markdown-task 0.6.0 
tree-view-copy-relative-path 1.1.0 
tree-view-git-status 1.3.1 
```
