### ISSUE TITLE
Uncaught TypeError: Cannot read property 'liveArchiveEditorMgr' of undefined

### ISSUE THREAD

**Issue by yasuyuki** [mark-hahn/live-archive#5]
[Enter steps to reproduce below:]

1. Open and close .live-archive/.gitignore

**Atom Version**: 0.176.0
**System**: Mac OS X 10.9.5
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.9

### Stack Trace

Uncaught TypeError: Cannot read property 'liveArchiveEditorMgr' of undefined

```
At /Volumes/ssd/y.inoue/.atom/packages/live-archive/lib/live-archive.coffee:43

TypeError: Cannot read property 'liveArchiveEditorMgr' of undefined
  at /Volumes/ssd/y.inoue/.atom/packages/live-archive/lib/live-archive.coffee:43:33
  at Emitter.module.exports.Emitter.emit (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.removeItem (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/pane.js:389:16)
  at Pane.module.exports.Pane.destroyItem (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/pane.js:457:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/workspace.js:716:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/workspace.js:760:21)
  at atom-workspace.atom.commands.add.core:close (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -0:49.8 core:close (div.release-notes.padded.pane-item.native-key-bindings)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus, v1.1.0
change-case, v0.4.0
dash, v1.0.2
japanese-wrap, v0.2.3
linter, v0.10.1
linter-rubocop, v0.2.1
live-archive, v0.1.9
rsense, v0.6.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by mark-hahn** [comment]
Fixed in 0.1.10.  Can you please test this for me?

**Comment by yasuyuki** [comment]
I tried this again. It has been fixed.

**Comment by mark-hahn** [comment]
Thanks for the report and testing.
