### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/adonisk/repos/redacted/.live-archive/.gitignore'

### ISSUE THREAD

**Issue by varemenos** [mark-hahn/live-archive#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.12

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/adonisk/repos/redacted/.live-archive/.gitignore'

```
At fs.js:503

Error: ENOENT, no such file or directory '/home/adonisk/repos/redacted/.live-archive/.gitignore'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1116:15)
  at /home/adonisk/.atom/packages/live-archive/lib/live-archive.coffee:53:31
  at process._tickCallback (node.js:364:11)

```

### Commands

```
  6x -0:10.2 click (div.header.list-item)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/home/adonisk/repos",
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "filetype-color",
      "git-history",
      "project-switcher",
      "tree-view-git-projects",
      "git-tab-status"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.0
autocomplete-css, v0.3.0
autocomplete-plus, v2.2.0
bezier-curve-editor, v0.6.5
color-picker, v1.4.4
docblockr, v0.6.3
editorconfig, v0.3.0
emmet, v2.3.4
file-icons, v1.5.0
git-projects, v1.8.1
hex, v0.5.0
highlight-line, v0.10.0
highlight-selected, v0.9.0
html-significant-other, v0.4.1
language-jade, v0.3.0
linter, v0.12.0
linter-jscs, v1.7.0
live-archive, v0.1.12
method-separator, v0.1.3
minimap, v4.3.1
minimap-find-and-replace, v4.1.0
minimap-git-diff, v4.0.0
minimap-highlight-selected, v4.1.0
monokai, v0.12.0
preview-plus, v1.1.19
regex-railroad-diagram, v0.7.1
select-line, v0.16.0
simple-drag-drop-text, v0.2.0
svg-preview, v0.5.1
symbols-tree-view, v0.6.1
sync-settings, v0.2.1
trailing-spaces, v0.2.4
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks for the report.

Fixed in 0.1.13.
